// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upglokpztbvjcjjeejhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwZ2xva3B6dGJ2amNqamVlamhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMDU0MjEsImV4cCI6MjA1NjU4MTQyMX0.9mqUtitoQSeujpZA1QNO9x53G09GY1t5JqImm_XuVA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);